# fly.toml app configuration file generated for green-cloud-2374 on 2023-11-08T11:06:32-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-cloud-2374"
primary_region = "lax"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
